<a href="https://colab.research.google.com/github/freemind988/WANG/blob/master/class03_hw3_%E7%8E%8B%E5%85%83%E6%81%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 第一題 空格數遞增，*數遞減
n = int(input())
for i in range(n):
    for j in range(i+1):   
        print(" ",end="")
    for k in range(n-i):    
        print("*",end="")
    print()

5
 *****
  ****
   ***
    **
     *


In [ ]:
# 第二題 空格數遞減，*數遞增
n = int(input())
for i in range(n):
    for j in range(n-i-1):  
        print(" ",end="")
    for k in range(i+1):   
        print("*",end="")
    print()

5
    *
   **
  ***
 ****
*****


In [ ]:
# 第三題 設計一個函式獲得兩點間的距離，請將程式碼完成 

import math

class Point:
  def __init__(self,x=0,y=0):
    self.x=x
    self.y=y
  def getx(self):
    return self.x
  def gety(self):
    return self.y

class Distance:
  def __init__(get_distance,p1,p2):
    get_distance.x=p1.getx()-p2.getx()
    get_distance.y=p1.gety()-p2.gety()
    # 用math.sqrt（）求平方根
    get_distance.len= math.sqrt((get_distance.x**2)+(get_distance.y**2))

  def get_len(self):
    return self.len

p1=Point(3,5)
p2=Point(10,29)
l=Distance(p1,p2)
l.get_len()

25.0

In [ ]:
# 使用者輸入兩個數字，第一個是 row，第二個是 column，產生一個 matrix
# 為 row x col，內部數值使用 random 函數，範圍定在 1 – 20 之間的整數。

import numpy as np

i = int(input("Row: "))
n = int(input("Col: "))
x = np.random.randint(low=1,high=20, size=(i,n))

print(x)


Row: 5
Col: 3
[[ 6 12 12]
 [ 5  9 14]
 [16 16  5]
 [18  8 15]
 [11  1  8]]


In [ ]:
# 第五題 HackerRank (USER_ID : freemind988@gmail.com)
# 截圖如附件所示